---
title: "test"
author: "Alfan"
date: "4/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require("httr")
require("jsonlite")
require("stringi")
require("spotifyr")
require("tidyverse")
```


```{r}
id <- "d6e8fbb83d7a4948a13a3f3f1962ae29"
secret <- "4bfd5b59bab3454f8e6510e2e9dc5d6a"

base <- "https://api.spotify.com/v1/"
```


```{r}
# Get Token 
token <- get_spotify_access_token(client_id = id,
  client_secret = secret)
token
```


```{r}
genreEndpoint <- "recommendations/available-genre-seeds"

callGenre <- paste(base,genreEndpoint, sep = "")
```


```{r}
getGenre <- GET(callGenre, add_headers(
  response_type = "code",
  Authorization = paste("Bearer ",token, sep = "")))

getGenre
```

```{r}
genre_text <- content(getGenre, "text")
get_genre <- fromJSON(genre_text, flatten = TRUE)
get_genre_df <- as.data.frame(get_genre)
get_genre_df
```

```{r}

#code for crawling recomenddation

# for (row in 1:nrow(get_genre_df)) {
#   genre = get_genre_df[row, "genres"]
#   limit = "100"
#   market = "ID"
#   print(genre)
#   recommendationsTracksEndPoint <- paste0("recommendations?limit=",
#                                           limit,"&market="
#                                           ,market,"&seed_genres="
#                                           ,genre)
#   callTracksByGenre <- paste0(base,recommendationsTracksEndPoint)
#   
#   pages <- list()
#   
#   for (i in 0:10) {
#     getTracksByGenre <- GET(callTracksByGenre,
#                           add_headers(
#                             Authorization = paste("Bearer ",token, sep = "")
#                           ))
#     tracksText <- content(getTracksByGenre, "text")
#     tracksJson <- fromJSON(tracksText, flatten = TRUE)
#     pages[[i+1]] <- tracksJson$tracks
#   }
#   
#   pages <- rbind_pages(pages)
#   pages <- pages %>% select(1:29)
#   pages <- pages %>% 
#     mutate(genre = genre)
#   
#   if (file.exists(paste0("./data/spotify/spotify-all-genre-recommendations.txt")) == TRUE) {
#     exist_pages <- source(paste0("./data/spotify/spotify-all-genre-recommendations.txt"))
#     exist_pages <- exist_pages$value
# 
#     pages <- rbind(pages, exist_pages)
#     pages <- subset(pages, !duplicated(pages$id))
#   }
# 
#   dput(pages, file=paste0("./data/spotify/spotify-all-genre-recommendations.txt"))
#   print(paste0("data for genre ",genre," finsih"))
#   exist_pages = NULL
# }

print("get data finish")

```



```{r}
if (file.exists(paste0("./data/spotify/spotify-all-genre-recommendations.txt")) == FALSE) {
  stop("Track data not exist")
}

tracks_all_df <- source(paste0("./data/spotify/spotify-all-genre-recommendations.txt"))
tracks_all_df <- tracks_all_df$value
```

```{r}
summary(tracks_all_df$genre)
```


```{r}
artists <- tracks_all_df[,1][[1]][1,]

for (row in 2:nrow(tracks_all_df)) {
  artists <- rbind(artists, tracks_all_df[,1][[row]][1,])
}

artists <- artists %>% 
  rename_all(funs(paste0("artist.",.)))

head(artists)
```

```{r}
album <- tracks_all_df[,16][[1]][1,]

for (row in 2:nrow(tracks_all_df)) {
  album <- rbind(album, tracks_all_df[,16][[row]][1,])
}

album <- album %>% 
  rename_all(funs(paste0("album.",.)))

head(album)
```




```{r}
album.img <- tracks_all_df[,19][[1]][1,]

for (row in 2:nrow(tracks_all_df)) {
  img <- tracks_all_df[,19][[row]][1,]
  if(is.null(img$url)) {
    img = c(height = NA, url = NA, width = NA)
  }
  album.img <- rbind(album.img, img)
}

album.img <- album.img %>% 
  rename_all(funs(paste0("album.img.",.)))

nrow(album.img)
head(album.img)
```


```{r}
tracks_all_df <- tracks_all_df %>% 
  select(-c("artists","album.artists","album.images"))

tracks_all_df <- cbind(tracks_all_df, artists, album, album.img)

head(tracks_all_df)
```

```{r}

if (file.exists(paste0("./data/spotify/spotify-all-genre-recommendations-list.csv")) == FALSE) {
 write.csv(tracks_all_df, file=paste0("./data/spotify/spotify-all-genre-recommendations-list.csv"), row.names = F) 
}

tracks_df <- read.csv("./data/spotify/spotify-all-genre-recommendations-list.csv")
```


```{r}
ids_df <- tracks_df %>% 
  select("id") %>% 
  mutate(id = as.character(id))

#code for crawling recomenddation
rep <- round(nrow(ids_df) / 30)

df_audio_feature <- data.frame()

audioFeatureEndPoint <- paste0("audio-features/?ids=")

for (row in 1:rep) {
  ids_list <- ids_df[,1]

  ids <- head(ids_list, 30)
  ids <- paste(ids, collapse =",")
  
  ids_df <- ids_df %>%
    slice(-(1:30))
  print(nrow(ids_df))
  
  callaudioFeature <- paste0(base,audioFeatureEndPoint,ids)
  getAudioFeatures <- GET(callaudioFeature,
                          add_headers(
                            Authorization = paste("Bearer ",token, sep = "")
                            ))
  tracksText <- content(getAudioFeatures, "text")
  tracksJson <- fromJSON(tracksText, flatten = TRUE)
  df_audio_feature <- rbind(df_audio_feature, tracksJson$audio_features)
}
```

```{r}
write.csv(df_audio_feature, file=paste0("./data/spotify/spotify-audiofeature-list.csv"), row.names = F)
```

